matrix:
include:
- os: osx
language: objective-c
osx_image: xcode12.4
script:
- set -o pipefail
- xcodebuild test -scheme XCTAssertNoLeak -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" | xcpretty -c
