matrix:
include:
- os: osx
language: objective-c
osx_image: xcode10.2
script:
- set -o pipefail
- xcodebuild test -scheme XCTAssertNoMemoryLeak -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty -c
